spring.datasource.url=jdbc:postgresql://ep-little-feather-aoq95x0h-pooler.c-2.ap-southeast-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_oy6UEKZv0zhR&sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_oy6UEKZv0zhR

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect